[package]
name = "encodedlua/rodux-dev-tools"
description = "Visualize and debug your Rodux state easier with tools to inspect actions and state"
license = "Apache-2.0"
authors = ["EncodedLua"]
version = "0.0.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Rodux = "roblox/rodux@3.0.0"
Roact = "roblox/roact@1.4.4"
RoduxHooks = "solarhorizon/rodux-hooks@0.3.1"
RoactHooks = "kampfkarren/roact-hooks@0.5.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
